routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/',[ 
    'as' => 'home',
    'uses' => 'HomeController@index'
    ]);
Route::get('paneladmin', 'PanelAdminController@index')->name('paneladmin');
Route::resource('paneluser', 'PanelUserController');

Route::get('catalogo',[ 
    'as' => 'catalogo',
    'uses' => 'HomeController@catalogo'
    ]);

Route::get('biz/{slug}', [
    'as' => 'biz-detail',
    'uses' => 'HomeController@show'
    ]);     
   
Auth::routes();
Route::get('search/','SearchController@search');

// Category dependency injection
Route::bind('category', function($category){
    return App\Category::find($category);
});

// User dependency injection
Route::bind('user', function($user){
    return App\User::find($user);
});

// User dependency injection
Route::bind('biz', function($biz){
    return App\Biz::find($biz);
});


//ADMIN

Route::resource('category', 'Panel\CategoryController');
Route::resource('user', 'Panel\UserController');
Route::resource('business', 'Panel\BusinessController');

app/Biz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Biz extends Model
{
    protected $table = 'bizs';

    protected $fillable = ['name', 'slug', 'description', 'extract', 'email', 'address', 'phone',  'image', 'visible', 
                           'category_id','user_id'];

    
    // Relation with Category
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    // Relation with USer
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function scopeSearch($query, $name)
    {

            return $query->where('name', 'LIKE', "%$name%")
                         ->orWhere('description', 'LIKE', "%$name%" );
        
        
    }
}

app/Http/Controllers/PanelUserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Biz;
use App\Category;
use App\User;

class PanelUserController extends Controller
{
    public function index()
    {
        //$bizs = Biz::find(1);
        //$bizs = Biz::where('user_id', '=', 1)->get();
        $bizs = Biz::orderBy('id', 'desc')->paginate();
        $bizs -> each(function ($bizs){
            $bizs -> category;
            $bizs -> user;
        });
        //dd($bizs);
        return view('paneluser.paneluser')
                  -> with('bizs', $bizs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::orderBy('id', 'desc')->pluck('name', 'id');
        $users = User::orderBy('id', 'desc')->pluck('name', 'id');
        //dd($categories);
      


        return view('paneluser.biz.create', compact('categories','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */

    public function store(SaveBizRequest $request)
    {
        $data = [
            'name'          => $request->get('name'),
            'slug'          => str_slug($request->get('name')),
            'description'   => $request->get('description'),
            'extract'       => $request->get('extract'),
            'address'       => $request->get('address'),
            'email'         => $request->get('email'),
            'phone'         => $request->get('phone'),
            'image'         => $request->get('image'),
            'visible'       => $request->has('visible') ? 1 : 0,
            'category_id'   => $request->get('category_id'),
            'user_id'       => $request->get('user_id')
        ];

        $business = Biz::create($data);

        $message = $business ? 'Negocio agregado correctamente!' : 'El negocio NO pudo agregarse!';
        
        return redirect()->route('paneluser.index')->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    /**public function show(Biz $business)
    {
        return $business;
    }

    
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit(Biz $business)
    {
        $categories = Category::orderBy('id', 'desc')->pluck('name', 'id');

        return view('paneluser.paneluser', compact('categories', 'business'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(SaveBizRequest $request, Biz $business)
    {
        

        $business->fill($request->all());
        $business->slug = str_slug($request->get('name'));
        $business->visible = $request->has('visible') ? 1 : 0;
        
        $updated = $business->save();
        
        $message = $updated ? 'Negocio actualizado correctamente!' : 'El negocio NO pudo actualizarse!';
        
        return redirect()->route('paneluser.index')->with('message', $message);
   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */

    public function destroy(Biz  $business)
    {
        $deleted = $business->delete();
        
        $message = $deleted ? 'Negocio eliminado correctamente!' : 'El negocio NO pudo eliminarse!';
        
        return redirect()->route('paneluser.index')->with('message', $message);
    }
}

resources/views/paneluser/biz/create.blade.php
@extends('paneluser.template')

@section('content')

<section class="">
    <div class="head4">
        <div class="row">
            <div class="col s12 m12 l12">
			 <div class="container text-center">
                <div class="page-header">
                    <h1>
                    NEGOCIOS <small>[Agregar negocios]</small>
                    </h1>
                </div>
             </div>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 offset-m3">
                <div class="page">
                    
                    @if (count($errors) > 0)
                        @include('partials.errors')
                    @endif
                    
                    {!! Form::open(['route'=>'paneluser.store','enctype="multipart/form-data"']) !!}
                        
                        <div>
                            <label class="" for="category_id">Categoría</label>
                            {!! Form::select('category_id', 
                                              $categories,  
                                              ['class' => 'form-control cate',
                                              'placeholder' => 'Selecciona una de las categorias',]) !!}
                        </div>
                        
                        
                        <div>
                            <label for="name">Nombre:</label>
                                
                                {!! 
                                    Form::text(
                                        'name', 
                                        null, 
                                        array(
                                            'class'=>'form-control',
                                            'placeholder' => 'Ingresa el nombre...',
                                            'autofocus' => 'autofocus'
                                        )
                                    ) 
                                !!}  
                        </div>

                        <div >
                            <label for="extract">Extracto:</label>
                                
                                {!! 
                                    Form::text(
                                        'extract', 
                                        null, 
                                        array(
                                            'class'=>'form-control',
                                            'placeholder' => 'Ingresa un pequeño extracto de la descripcion...',
                                        )
                                    ) 
                                !!}
                        </div>

                        <div class="form-group">
                            <label for="description">Descripción:</label>
                            
                            {!! 
                                Form::textarea(
                                    'description', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa la descripcion completa...',
                                    )
                                ) 
                            !!}
                        </div>
                        
                        <div class="form-group">
                            <label for="address">Direccion:</label>
                            
                            {!! 
                                Form::text(
                                    'address', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa la direccion del negocio...',
                                    )
                                ) 
                            !!}
                        </div>
                        
                        <div class="form-group">
                            <label for="email">Correo Electronico:</label>
                            
                            {!! 
                                Form::text(
                                    'email', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa el correo electronico de tu negocio...',
                                    )
                                ) 
                            !!}
                        </div>

                        <div class="form-group">
                            <label for="phone">Telefono:</label>
                            
                            {!! 
                                Form::text(
                                    'phone', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa el telefono...',
                                    )
                                ) 
                            !!}
                        </div>

                        <div class="form-group">
                            <label for="image">Imagen:</label>
                            
                            {!! 
                                Form::file(
                                    'image', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa la url de la imagen...',
                                    )
                                ) 
                            !!}
                        </div>
                        
                       

                        <div class="form-group">
                        <label for="visible">Visible:  </label>
                        
                        <label>
                            <input type="checkbox" name="visible" value="visible" checked="checked"/>
                             <span></span>
                        </label>
                           
                        </div>
                        {!! 
                            Form::text(
                                'user_id', 
                                Auth::user()->id, 
                                array('class'=>'form-control userid')) 
                        !!} 
                        
                        <div class="form-group">
                            {!! Form::submit('Guardar', array('class'=>'btn btn-primary')) !!}
                            <a href="{{ route('paneluser.index') }}" class="btn btn-warning">Cancelar</a>
                        </div>
                    
                    {!! Form::close() !!}
                    </div>
                    

                </div>
            </div>
        </div>   
        
    </div>
</section>


		
        

@stop


        

resources/views/paneluser/biz/edit.blade.php
@extends('paneluser.template')

@section('content')

<section class="">
    <div class="head4">
        <div class="row">
            <div class="col s12 m12 l12">
			 <div class="container text-center">
                <div class="page-header">
                    <h1>
                    NEGOCIOS <small>[editar negocio]</small>
                    </h1>
                </div>
             </div>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s6 offset-m3">
                <div class="page">
                    
                    @if (count($errors) > 0)
                        @include('partials.errors')
                    @endif
                    
                    {!! Form::model($business, array('route' => array('paneluser.update', $business))) !!}
                    <input type="hidden" name="_method" value="PUT">
                        <div>
                            <label class="" for="category_id">Categoría</label>
                            {!! Form::select('category_id', 
                                              $categories, 
                                              555, 
                                              ['class' => 'form-control cate',
                                              'placeholder' => 'Selecciona una de las categorias',]) !!}
                        </div>
                        
                        
                        
                        <div>
                            <label for="name">Nombre:</label>
                                
                                {!! 
                                    Form::text(
                                        'name', 
                                        null, 
                                        array(
                                            'class'=>'form-control',
                                            'placeholder' => 'Ingresa el nombre...',
                                            'autofocus' => 'autofocus'
                                        )
                                    ) 
                                !!}  
                        </div>

                        <div >
                            <label for="extract">Extracto:</label>
                                
                                {!! 
                                    Form::text(
                                        'extract', 
                                        null, 
                                        array(
                                            'class'=>'form-control',
                                            'placeholder' => 'Ingresa un pequeño extracto de la descripcion...',
                                        )
                                    ) 
                                !!}
                        </div>

                        <div class="form-group">
                            <label for="description">Descripción:</label>
                            
                            {!! 
                                Form::textarea(
                                    'description', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa la descripcion completa...',
                                    )
                                ) 
                            !!}
                        </div>
                        
                        <div class="form-group">
                            <label for="address">Direccion:</label>
                            
                            {!! 
                                Form::text(
                                    'address', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa la direccion del negocio...',
                                    )
                                ) 
                            !!}
                        </div>
                        
                        <div class="form-group">
                            <label for="email">Correo Electronico:</label>
                            
                            {!! 
                                Form::text(
                                    'email', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa el correo electronico de tu negocio...',
                                    )
                                ) 
                            !!}
                        </div>

                        <div class="form-group">
                            <label for="phone">Telefono:</label>
                            
                            {!! 
                                Form::text(
                                    'phone', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa el telefono...',
                                    )
                                ) 
                            !!}
                        </div>

                        <div class="form-group">
                            <label for="image">Imagen:</label>
                            
                            {!! 
                                Form::text(
                                    'image', 
                                    null, 
                                    array(
                                        'class'=>'form-control',
                                        'placeholder' => 'Ingresa la url de la imagen...',
                                    )
                                ) 
                            !!}
                        </div>
                        
                       

                        <div class="form-group">
                        <label for="visible">Visible:  </label>
                        
                        <label>
                            <input type="checkbox" name="visible" value="visible" checked="checked"/>
                             <span></span>
                        </label>
                           
                        </div>
                        
                        <div class="form-group">
                            {!! Form::submit('Actualizar', array('class'=>'btn btn-primary')) !!}
                            <a href="{{ route('paneluser.index') }}" class="btn btn-warning">Cancelar</a>
                        </div>
                    
                    {!! Form::close() !!}
                    </div>
                    

                </div>
            </div>
        </div>   
        
    </div>
</section>


		
        

@stop


        

resources/views/paneluser/biz/index.blade.php
@extends('panel.template')
  
@section('content')
<section class="">
  <div class="head4">
    <div class="row">
        <div class="col s12 m12 l12">
			<div class="container text-center">
			<div class="page-header">
				<h1>
					NEGOCIOS <a href="{{ route('business.create') }}" class="waves-effect waves-light btn-small"><i class="material-icons left">add_circle_outline</i>Negocios</a>
				</h1>
			</div>
			<div class="page">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover">
						<thead>
                            <tr>
                                <th>Editar</th>
                                <th>Eliminar</th>
                                <th>Imagen</th>
                                <th>Nombre</th>
                                <th>Categoría</th>
                                <th>Extracto</th>
                                <th>usuario</th>
                                <th>Visible</th>
                            </tr>
						</thead>
						<tbody>
							@foreach($bizs as $business)
								<tr>
									<td>
									<a href="{{ route('business.edit', $business) }}" class="btn-floating btn-large waves-effect waves-light blue">
									<i class="material-icons left">brush</i></a>
									</td>
									
									<td>
										{!! Form::open(['route' => ['business.destroy', $business]]) !!}
											<input type="hidden" name="_method" value="DELETE">
											<button  class="btn-floating btn-large waves-effect waves-light red">
												<i class="material-icons left">delete_forever</i>
											</button>
										{!! Form::close() !!}
									</td>
                                    <td><img src="{{ $business->image }}" width="40"></td>
                                    <td>{{ $business->name }}</td>
                                    <td>{{ $business->category->name }}</td>
                                    <td>{{ $business->extract }}</td>
									<td>{{ $business->user->name }}</td>
                                    <td>{{ $business->visible == 1 ? "Si" : "No" }}</td>
									
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
                <hr>
            
            <?php echo $bizs->render(); ?>
			</div>

		</div>
        </div>
    </div>
  </div>
</section>

	
	
@stop