routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/',[ 
    'as' => 'home',
    'uses' => 'HomeController@index'
    ]);
Route::get('paneladmin', 'PanelAdminController@index')->name('paneladmin');
Route::resource('paneluser', 'PanelUserController');

Route::get('catalogo',[ 
    'as' => 'catalogo',
    'uses' => 'HomeController@catalogo'
    ]);

Route::get('biz/{slug}', [
    'as' => 'biz-detail',
    'uses' => 'HomeController@show'
    ]);     
   
Auth::routes();
Route::get('search/','SearchController@search');

// Category dependency injection
Route::bind('category', function($category){
    return App\Category::find($category);
});

// User dependency injection
Route::bind('user', function($user){
    return App\User::find($user);
});

// User dependency injection
Route::bind('biz', function($biz){
    return App\Biz::find($biz);
});


//ADMIN

Route::resource('category', 'Panel\CategoryController');
Route::resource('user', 'Panel\UserController');
Route::resource('business', 'Panel\BusinessController');

app/Http/Controllers/PanelAdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PanelAdminController extends Controller
{
    public function index()
    {
        return view('paneladmin/paneladmin');
    }
}

resources/views/paneladmin/paneladmin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">PANEL DE ADMINISTRACION</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="col m6">
                        <div class="panel">
                            <i class="fa fa-list-alt icon-home"></i>
                            <a href="{{ route('category.index') }}" class="btn btn-warning btn-block btn-home-admin">CATEGORÍAS</a>
                        </div>
                    </div>

                    <div class="col m6">
                        <div class="panel">
                            <i class="fa fa-shopping-cart  icon-home"></i>
                            <a href="{{ route('user.index') }}" class="btn btn-warning btn-block btn-home-admin">USUARIOS</a>
                        </div>
                    </div>

                    <div class="col m6">
                        <div class="panel">
                            <i class="fa fa-shopping-cart  icon-home"></i>
                            <a href="{{ route('business.index') }}" class="btn btn-warning btn-block btn-home-admin">negocios</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

     
</div>
@endsection

resources/views/paneladmin/template.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>@yield('title','negomex')</title>

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="{{ asset('css/styles.css') }}"  media="screen,projection"/>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

</head>
<body>


    @include('partials.nav')

    @yield('content')

    @include('partials.footer')
    
  
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="{{ asset('js/materialize.min.js') }}"></script>
  <script type="text/javascript" charset="utf-8">
      $(document).ready(function(){
        $(".dropdown-trigger").dropdown();
        $('select').formSelect();
      });

       $(document).ready(function(){
          $('select').formSelect();
        });

  </script>
</body>
</html>