routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|


Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/',[ 
    'as' => 'home',
    'uses' => 'HomeController@index'
    ]);
Route::get('paneladmin', 'PanelAdminController@index')->name('paneladmin');
Route::resource('paneluser', 'PanelUserController');

Route::get('catalogo',[ 
    'as' => 'catalogo',
    'uses' => 'HomeController@catalogo'
    ]);

Route::get('biz/{slug}', [
    'as' => 'biz-detail',
    'uses' => 'HomeController@show'
    ]);     
   
Auth::routes();
Route::get('search/','SearchController@search');

// Category dependency injection
Route::bind('category', function($category){
    return App\Category::find($category);
});

// User dependency injection
Route::bind('user', function($user){
    return App\User::find($user);
});

// User dependency injection
Route::bind('biz', function($biz){
    return App\Biz::find($biz);
});


//ADMIN

Route::resource('category', 'Panel\CategoryController');
Route::resource('user', 'Panel\UserController');
Route::resource('business', 'Panel\BusinessController');

app/Http/Controllers/PanelUserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Biz;
use App\Category;
use App\User;

class PanelUserController extends Controller
{
    public function index()
    {
        //$bizs = Biz::find(1);
        //$bizs = Biz::where('user_id', '=', 1)->get();
        $bizs = Biz::orderBy('id', 'desc')->paginate();
        $bizs -> each(function ($bizs){
            $bizs -> category;
            $bizs -> user;
        });
        //dd($bizs);
        return view('paneluser.paneluser')
                  -> with('bizs', $bizs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $categories = Category::orderBy('id', 'desc')->pluck('name', 'id');
        $users = User::orderBy('id', 'desc')->pluck('name', 'id');
        //dd($categories);
      


        return view('paneluser.biz.create', compact('categories','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */

    public function store(SaveBizRequest $request)
    {
        $data = [
            'name'          => $request->get('name'),
            'slug'          => str_slug($request->get('name')),
            'description'   => $request->get('description'),
            'extract'       => $request->get('extract'),
            'address'       => $request->get('address'),
            'email'         => $request->get('email'),
            'phone'         => $request->get('phone'),
            'image'         => $request->get('image'),
            'visible'       => $request->has('visible') ? 1 : 0,
            'category_id'   => $request->get('category_id'),
            'user_id'       => $request->get('user_id')
        ];

        $business = Biz::create($data);

        $message = $business ? 'Negocio agregado correctamente!' : 'El negocio NO pudo agregarse!';
        
        return redirect()->route('paneluser.index')->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    /**public function show(Biz $business)
    {
        return $business;
    }

    
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit(Biz $business)
    {
        $categories = Category::orderBy('id', 'desc')->pluck('name', 'id');

        return view('paneluser.paneluser', compact('categories', 'business'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(SaveBizRequest $request, Biz $business)
    {
        

        $business->fill($request->all());
        $business->slug = str_slug($request->get('name'));
        $business->visible = $request->has('visible') ? 1 : 0;
        
        $updated = $business->save();
        
        $message = $updated ? 'Negocio actualizado correctamente!' : 'El negocio NO pudo actualizarse!';
        
        return redirect()->route('paneluser.index')->with('message', $message);
   
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */

    public function destroy(Biz  $business)
    {
        $deleted = $business->delete();
        
        $message = $deleted ? 'Negocio eliminado correctamente!' : 'El negocio NO pudo eliminarse!';
        
        return redirect()->route('paneluser.index')->with('message', $message);
    }
}

resources/views/paneluser/paneluser.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
            </div>
            
            <div class="table-responsive">
				<h3>Datos del usuario</h3>
				<table class="table table-striped table-hover table-bordered">
					<tr><td>Nombre:</td><td>{{ Auth::user()->name . " " . Auth::user()->last_name }}</td></tr>
					<tr><td>Usuario:</td><td>{{ Auth::user()->user }}</td></tr>
					<tr><td>Correo:</td><td>{{ Auth::user()->email }}</td></tr>
					<tr><td>Dirección:</td><td>{{ Auth::user()->address }}</td></tr>
				</table>
            </div>
        </div>

        <div class="col s12 m12 l12">
			<div class="container text-center">
			<div class="page-header">
				<h1>
					NEGOCIOS <a href="{{ route('paneluser.create') }}" class="waves-effect waves-light btn-small"><i class="material-icons left">add_circle_outline</i>Negocios</a>
				</h1>
			</div>
			<div class="page">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover">
						<thead>
                            <tr>
                                <th>Editar</th>
                                <th>Eliminar</th>
                                <th>Imagen</th>
                                <th>Nombre</th>
                                <th>Categoría</th>
                                <th>Extracto</th>
                                <th>usuario</th>
                                <th>Visible</th>
                            </tr>
						</thead>
						<tbody>
							@foreach($bizs as $business)
								<tr>
									<td>
									<a href="{{ route('paneluser.edit', $business) }}" class="btn-floating btn-large waves-effect waves-light blue">
									<i class="material-icons left">brush</i></a>
									</td>
									
									<td>
										{!! Form::open(['route' => ['paneluser.destroy', $business]]) !!}
											<input type="hidden" name="_method" value="DELETE">
											<button  class="btn-floating btn-large waves-effect waves-light red">
												<i class="material-icons left">delete_forever</i>
											</button>
										{!! Form::close() !!}
									</td>
                                    <td><img src="{{ $business->image }}" width="40"></td>
                                    <td>{{ $business->name }}</td>
                                    <td>{{ $business->category->name }}</td>
                                    <td>{{ $business->extract }}</td>
									<td>{{ $business->user->name }}</td>
                                    <td>{{ $business->visible == 1 ? "Si" : "No" }}</td>
									
								</tr>
							@endforeach
						</tbody>
					</table>
				</div>
                <hr>
            
            <?php echo $bizs->render(); ?>
			</div>

		</div>
        </div>
    </div>
</div>
@endsection

resources/views/paneluser/template.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>@yield('title','negomex')</title>

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
  <link type="text/css" rel="stylesheet" href="{{ asset('css/styles.css') }}"  media="screen,projection"/>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

</head>
<body>


    @include('partials.nav')

    @yield('content')

    @include('partials.footer')
    
  
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
  <script src="{{ asset('js/materialize.min.js') }}"></script>
  <script type="text/javascript" charset="utf-8">
      $(document).ready(function(){
        $(".dropdown-trigger").dropdown();
        $('select').formSelect();
      });

       $(document).ready(function(){
          $('select').formSelect();
        });

  </script>
</body>
</html>